api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('list/', views.api, name='api-index'),
    path('list/', views.APIListView.as_view(), name='api-index'),
    # path('view/<str:pk>/', views.api_view, name='api-view'),
    path('view/<str:pk>/', views.APIGetView.as_view(), name='api-view'),
    path('delete/<str:pk>/', views.APIDeleteView.as_view(), name='api-delete'),
    path('add/', views.APICreateView.as_view(), name='api-add'),
    path('update/<str:pk>/', views.APIUpdateView.as_view(), name='api-update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')), # not necessary
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.hello, name='hello-index'),
    path('view/<str:pk>/', views.hello_view, name='hello-view'),
    path('delete/<str:pk>/', views.hello_delete, name='hello-delete'),
    path('add/', views.hello_add, name='hello-add'),
    path('update/<str:pk>/', views.hello_update, name='hello-update'),
]

api/models.py
from django.db import models

# Create your models here.

class Action(models.Model):
    text = models.CharField(max_length=255)
    description = models.CharField(max_length=255, default='something')

    def __str__(self):
        return self.text

hello/forms.py
from django import forms


class ActionAddForm(forms.Form):
    text = forms.CharField(max_length=255)
    description = forms.CharField(max_length=255)


class ActionUpdateForm(ActionAddForm):
    pass



# modelForm
from . import models

class ActionAddModelForm(forms.ModelForm):
    # text = forms.CharField(max_length=255)
    # description = forms.CharField(max_length=255)

    class Meta:
        model = models.Action
        fields = ['text', 'description'] # can be '__all__' if all were needed
        # exclude = [] if want some other but not the specified field in the exclude


class ActionUpdateModelForm(ActionAddModelForm):
    pass

api/views.py
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response # NOTE THIS INSTEAD OF HTTPRESPONSE OR RENDER we use this
from rest_framework.views import APIView

from django.views.decorators.csrf import csrf_exempt
# https://www.django-rest-framework.org/api-guide/views/

from rest_framework.parsers import JSONParser

from rest_framework.permissions import AllowAny

from . import models
from . import serializers # note were not using forms


# v1
# @api_view() # GET by default  @api_view(['GET'])
# def api(request):
#     context = {
#         'name': 'Miguel',
#         #'to_do': models.Action.objects.all(), # this will cause an error, all data should be serialize or non-object
#         'to_do': models.Action.objects.all().values('id', 'text', 'description')

#         # another approach was to use serialize as outside response
#         # 'to_do': serializers.ActionSerializer(models.Action.objects.all(), many=True).data
#         # https://www.django-rest-framework.org/api-guide/serializers/
#         # this approach is much better
#     }
#     return Response(context) # status by default is 200

# @api_view()
# def api_view(request, pk):
#     obj = get_object_or_404(models.Action, pk=pk)
#     # NOTE IN THIS FUNCTION WERE ONLY FOCUSING ON TRANSFERRING BACK A SERIALIZED OBJECT
#     # AND NOT WORRYING ABOUT TEMPLATES OR REDIRECTS
#     return Response({'data':serializers.ActionSerializer(obj).data})


class APIListView(APIView):
    def get(self, request):
        context = {
        'name': 'Miguel',
        'to_do': serializers.ActionSerializer(models.Action.objects.all(), many=True).data
        # https://www.django-rest-framework.org/api-guide/serializers/
        }
        return Response(context)


class APIGetView(APIView):
    def get(self, request, pk):
        obj = get_object_or_404(models.Action, pk=pk)
        return Response({'data':serializers.ActionSerializer(obj).data})


# FOR SOME REASON api_view decorator is bugging therefore use this

class APIDeleteView(APIView):

    def delete(self, request, pk):
        obj = get_object_or_404(models.Action, pk=pk)
        obj.delete()
        return Response({'data': True})


class APICreateView(APIView):
    def post(self, request):
        serializer = serializers.ActionAddSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        obj = models.Action.objects.create(**serializer.validated_data)
        return Response(serializers.ActionSerializer(obj).data)


class APIUpdateView(APIView):
    def put(self, request, pk):
        obj = get_object_or_404(models.Action, pk=pk)
        serializer = serializers.ActionUpdateSerializer(obj, data=request.data)
        serializer.is_valid(raise_exception=True)

        # normal
        for k, v in serializer.validated_data.items():
            setattr(obj, k, v)
        obj.save()

        return Response(serializers.ActionSerializer(obj).data)


# DIY, make a model serializer counterpart of those serializer :)
# Another there was a create and update method in the serializer itself

hello/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect

from . import models # v5
from . import forms # 6

# v1
# def hello(request):
#     return HttpResponse("Hello World")

# v2
# https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#django.shortcuts.render
def hello(request):
    # return render(request, 'hello.html')

    # v3
    # return render(request, 'hello.html', {'name': 'THE AUTHOR OF THIS APP'})

    # v4
    # https://docs.djangoproject.com/en/3.2/ref/templates/builtins/
    # context = {
    #     'name': 'Miguel', # change the name
    #     'to_do': [
    #         'homework',
    #         'cleaning mugs',
    #         'study',
    #         'gdsc study jam',
    #     ]
    # }
    # return render(request, 'hello.html', context)

    # v5 cont
    # context = {
    #     'name': 'Miguel',
    #     'to_do': models.Action.objects.all(),
    #     # 'to_do': models.Action.objects.all().values_list('text', flat=True),
    # }
    # return render(request, 'hello.html', context)

    # v6
    # by default once the page was loaded it tries a GET METHOD
    # if request.method == 'GET':
    #     # raise Exception(True)

    #     context = {
    #         'name': 'Miguel',
    #         'to_do': models.Action.objects.all(),
    #         # 'to_do': models.Action.objects.all().values_list('text', flat=True),
    #     }
    #     return render(request, 'hello.html', context)

    # v7
    context = {
        'create_or_update': forms.ActionAddForm()
    }
    return render(request, 'hello.html', context)

def hello_view(request, pk):
    if request.method == 'GET':
        obj = get_object_or_404(models.Action, pk=pk)
        return render(request, 'hello-view.html', {'data': obj})
    return HttpResponseRedirect(reverse('hello-index'))

def hello_delete(request, pk):
    obj = get_object_or_404(models.Action, pk=pk)
    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect(reverse('hello-index'))
    return render(request, 'hello-delete.html', {'data': obj})


def hello_add(request):
    context = {}
    form = forms.ActionAddForm()

    if request.method == 'POST':

        # normal form
        form = forms.ActionAddForm(request.POST)
        if form.is_valid():
            models.Action.objects.create(**form.cleaned_data)

        # modelform
        # form = forms.ActionAddModelForm(request.POST)
        # if form.is_valid(): form.save()

        return HttpResponseRedirect(reverse('hello-index'))
    context['form'] = form
    return render(request, 'hello-add.html', context)


def hello_update(request, pk ):
    obj = get_object_or_404(models.Action, pk=pk)

    context = {}
    form = forms.ActionUpdateForm()

    # manually initialize all values from object to the form
    form.fields['text'].initial = obj.text
    form.fields['description'].initial = obj.description

    if request.method == 'POST':
        # normal form
        form = forms.ActionUpdateForm(request.POST)
        if form.is_valid():
            for k, v in form.cleaned_data.items():
                setattr(obj, k, v)
            obj.save()
        return HttpResponseRedirect(reverse('hello-index'))
    context['form'] = form
    context['data'] = obj

    # modelform version
    # context = {}
    # form = forms.ActionUpdateModelForm(instance=obj)
    # if request.method == 'POST':
        # form = forms.ActionUpdateModelForm(request.POST, instance=obj)
        # if form.is_valid(): form.save()

    return render(request, 'hello-update.html', context)

hello/templates/hello-add.html
<head>
    <title>TO DO APP</title>
    <!-- to do: the proper of static
        https://docs.djangoproject.com/en/3.2/howto/static-files/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        ul {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <center>
        <h1>Add object</h1>
        <br>
        <br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Confirm" /> | <a href="{% url 'hello-index' %}">Go back</a>
        </form>
    </center>
</body>

hello/templates/hello-delete.html
<head>
    <title>TO DO APP</title>
    <!-- to do: the proper of static
        https://docs.djangoproject.com/en/3.2/howto/static-files/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        ul {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <center>
        <h1>Delete object</h1>
        <br>
        <br>
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ data.text }}"?</p>
            <input type="submit" value="Confirm" /> | <a href="{% url 'hello-index' %}">Go back</a>
        </form>
    </center>
</body>

hello/templates/hello-update.html
<head>
    <title>TO DO APP</title>
    <!-- to do: the proper of static
        https://docs.djangoproject.com/en/3.2/howto/static-files/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        ul {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <center>
        <h1>Update object {{ data.text }}</h1>
        <br>
        <br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Confirm" /> | <a href="{% url 'hello-index' %}">Go back</a>
        </form>
    </center>
</body>

hello/templates/hello-view.html
<head>
    <title>TO DO APP</title>
    <!-- to do: the proper of static
        https://docs.djangoproject.com/en/3.2/howto/static-files/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        ul {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <center>
        <h1>View object</h1>
        <br>
        <br>
        <h1>{{ data.text }}</h1>
        <br>
        <h3>{{ data.description }}</h3>
    <a href="{% url 'hello-index' %}">Go back</a>
    </center>
</body>

hello/templates/hello.html
<head>
    <title>TO DO APP</title>
    <!-- to do: the proper of static
        https://docs.djangoproject.com/en/3.2/howto/static-files/ -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        ul {
            list-style-type: none;
        }
    </style>
</head>
<body>
    <!-- <h1>TO DO APP</h1> -->
    <!-- <center><h2><p>To do app : {{ name }}<p></h2></center>
    <br>
    <center><a href="{% url 'hello-add' %}">Add Action </a></center>
    <br>
    <div class="d-flex justify-content-center">
        <table class='text-center'>
            <thead>
                <tr>
                 <th> <h2> Activities </h2> </th>
                 <th><h2> Actions </h2></th>
                <tr>
            </thead>

            {% for t in to_do %}
            <tr>
                <td><h3>{{ t.text }}</h3></td>
                <td>
                    <a href="{% url 'hello-view' t.pk %}"> View</a>
                    <a href="{% url 'hello-update' t.pk %}"> Update</a>
                    <a href="{% url 'hello-delete' t.pk %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div> -->

    <center><h2><p id='namePlease'>To do app : None <p></h2></center>
    <center><button class="add" name="Add" onclick='addAction(this)'>Add Action</button></center>
    <br>
    <br>
    <div class="d-flex justify-content-center">
        <table class='text-center'>
            <thead>
                <tr>
                 <th> <h2> Activities </h2> </th>
                 <th><h2> Actions </h2></th>
                <tr>
            </thead>

            <tbody id='bodyAction'></tbody>
        </table>
    </div>
    <br>
    <br>
    <center>Add or Update Form</center>
    <center>Push add button if you want to add, else update if you want to update</center>
    <div class="d-flex justify-content-center">

        <form id='actionForm'>
            {{ create_or_update.as_ul }}
        </form>
    </div>

    {% csrf_token %}
    <script>
        // list
        $.ajax({
            type: 'GET',
            url: '/api/list/',
            success: function(resp){
                var data = resp;
                console.log(data);
                $('#namePlease').text("To do app" + ' : ' +  data.name);

                for(let i=0; i < data.to_do.length; i++){
                    var item = data.to_do[i];

                    $('#bodyAction').append(
                    `<tr id=${i}>
                        <td id="actionText">
                            <h3 id="actionTextHeader"> ${ item.text } </h3>
                        </td>
                        <td id="actionButton">
                            <button class="view" name="view" value=${item.id} onclick="viewAction(this)">View</button>
                            <button class="update" name="view" value=${item.id} onclick="updateAction(this,  ${i})">Update</button>
                            <button class="delete" name="delete" value=${item.id} onclick="deleteAction(this, ${i})">Delete</button>
                        </td>
                    </tr>
                    `
                    )
                }
            },
            error: function(resp){
                console.log(resp);
            }
        })

        // get
        function viewAction(obj){
            console.log(obj.value);
            $.ajax({
                type: 'GET',
                url: `/api/view/${obj.value}/`,
                success: function(resp){
                    var data = resp.data;
                    alert(`id: ${data.id} - text: ${data.text} - description: ${data.description}`)
                },
                error: function(resp){
                    console.log(resp);
                }
            })
        }

        // https://docs.djangoproject.com/en/3.2/ref/csrf/
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        console.log(csrftoken);

        // delete
        function deleteAction(obj, index){
            console.log(index);
            if(confirm('Are you sure you want to delete it?')){
                console.log(this);
                $.ajax({
                    url: `/api/delete/${obj.value}/`,
                    type: 'DELETE',
                    headers: {'X-CSRFToken': csrftoken},
                    data: {},
                    success: function(resp){
                        $('#bodyAction').find('tr')[index].remove();
                    },
                    error: function(resp){
                        console.log(resp);
                    }
                })
            }

        }

        // add
        function addAction(obj){
            console.log(obj);
            // targeted fields
            var text = $('#id_text').val();
            var description = $('#id_description').val();
            console.log(text + ' ' + description);

            $.ajax({
                url: `/api/add/`,
                type: 'POST',
                headers: {'X-CSRFToken': csrftoken},
                data: {
                    'text': text,
                    'description': description
                },
                success: function(resp){
                    var data = resp
                    var rowCount = $('#bodyAction tr').length;
                    $('#bodyAction').append(
                        `<tr id=${rowCount}>
                        <td id="actionText">
                            <h3> ${data.text} </h3>
                        </td id="actionButton">
                        <td>
                            <button class="view" name="view" value=${data.id} onclick="viewAction(this)">View</button>
                            <button class="update" name="view" value=${data.id} onclick="updateAction(this, ${rowCount})">Update</button>
                            <button class="delete" name="delete" value=${data.id} onclick="deleteAction(this, ${rowCount})">Delete</button>
                        </td>
                    </tr>
                    `
                    )
                },
                error: function(resp){
                    alert(resp.responseText);
                }
            })
        }

        // update
        function updateAction(obj, index){
            var text = $('#id_text').val();
            var description = $('#id_description').val();

            $.ajax({
                url: `/api/update/${obj.value}/`,
                type: 'PUT',
                headers: {'X-CSRFToken': csrftoken},
                data: {
                    'id': obj.value,
                    'text': text,
                    'description': description
                },
                success: function(resp){
                    console.log($(`#${index} td h3`).html(resp.text));
                    $('#actionTextHeader').val(resp.text);
                },
                error: function(resp){
                    alert(resp.responseText);
                }
            })
        }

    </script>

</body>